### ISSUE TITLE
Few doubts on configuring tensorflow object detection api for face detection

### ISSUE THREAD

**Issue by vaishnavm217** [qdraw/tensorflow-face-object-detector-tutorial#1]
Hi,
I am trying the same experiment mentioned in this repo. I have few doubts:

1. I went through your code and what i understood was you converted annotations to xml then to csv, then to tfrecord with images. I directly converted txt file to tfrecord with images. Will this be a problem?
2. I noticed you've used HOG in one of the files. I don't understand the use of it here.
3. In eval script, I am getting the same warning `WARNING:root:The following classes have no ground truth examples: 1`, but after this my program terminates giving this error:
```
mean_ap = np.nanmean(self.average_precision_per_class)
/home/vaishnav/models/research/object_detection/utils/object_detection_evaluation.py:586: RuntimeWarning: Mean of empty slice
  mean_corloc = np.nanmean(self.corloc_per_class)
Traceback (most recent call last):
  File "object_detection/eval.py", line 130, in <module>
    tf.app.run()
  File "/home/vaishnav/cv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/eval.py", line 126, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/vaishnav/models/research/object_detection/evaluator.py", line 210, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/home/vaishnav/models/research/object_detection/eval_util.py", line 381, in repeated_checkpoint_run
    save_graph_dir)
  File "/home/vaishnav/models/research/object_detection/eval_util.py", line 269, in _run_checkpoint_once
    image_id=batch, groundtruth_dict=result_dict)
  File "/home/vaishnav/models/research/object_detection/utils/object_detection_evaluation.py", line 174, in add_single_ground_truth_image_info
    standard_fields.InputDataFields.groundtruth_difficult, None))
  File "/home/vaishnav/models/research/object_detection/utils/object_detection_evaluation.py", line 447, in add_single_ground_truth_image_info
    groundtruth_is_group_of_list.astype(dtype=bool))
  File "/home/vaishnav/models/research/object_detection/utils/object_detection_evaluation.py", line 527, in _update_ground_truth_statistics
    & ~groundtruth_is_group_of_list] == class_index)
ValueError: operands could not be broadcast together with shapes (0,) (126,) 
```
did you encounter this? I thought this might be due to single class used in face detection.

**Comment by qdraw** [comment]
`I directly converted txt file to tfrecord with images`
Did you include the location of the box in the tfrecord input?

**Comment by vaishnavm217** [comment]
Yup . That too normalized as mentioned in the readme

**Comment by qdraw** [comment]
I've found a thread on the official repo: https://github.com/tensorflow/models/issues/2713 and stack-overflow: https://stackoverflow.com/a/24564015. What data did you feed? Are the object annotations correct? What do you mean with HOG?

**Comment by vaishnavm217** [comment]
This  https://github.com/tensorflow/models/issues/2713 I think it worked,
although after 600 steps it's showing weird boxes in tensorboard
I'll check the progress after lot of training. Thanks for the help :)

**Comment by qdraw** [comment]
Your welcome, no problem.
What do you mean with HOG?

**Comment by vaishnavm217** [comment]
>  What do you mean with HOG?

In [002_data-to-pascal-xml.py](https://github.com/qdraw/tensorflow-face-object-detector-tutorial/blob/master/002_data-to-pascal-xml.py), you used
```
hog = cv2.HOGDescriptor((80, 80), (16, 16), (8,8), (8,8), 9)
```

Moreover after like 6k epochs, tensorboard is displaying no boxes in images section. I will try running the model manually and see if any problem comes up

**Comment by vaishnavm217** [comment]
They Fixed the code in recent commit. Working perfectly. Thanks a lot. Closes this issue!
