### ISSUE TITLE
NotFoundError

### ISSUE THREAD

**Issue by EigenvectorOfFate** [qdraw/tensorflow-face-object-detector-tutorial#2]
> NotFoundError: /data/git/tensorflow-face-object-detector-tutorial/face_label.pbtxt; No such file or directory.

When I run the code following: python ~/models/research/object_detection/train.py --logtostderr --pipeline_config_path=ssd_mobilenet_v1_face.config  --train_dir=model_output, I get this error. But I did't find face_label.pbtxt, how to download this file?

**Comment by qdraw** [comment]
You Can find this file here: https://github.com/qdraw/tensorflow-face-object-detector-tutorial/blob/master/face_label.pbtxt
