### ISSUE TITLE
ssd_mobilenet_v1_coco_11_06_2017

### ISSUE THREAD

**Issue by elhammoumi** [qdraw/tensorflow-face-object-detector-tutorial#3]
/data/git/tensorflow-face-object-detector-tutorial/data/ssd_mobilenet_v1_coco_11_06_2017 : The system cannot find the path specified.

**Comment by qdraw** [comment]
Please update the path to your filesystem in this file: https://github.com/qdraw/tensorflow-face-object-detector-tutorial/blob/master/ssd_mobilenet_v1_face.config and here: https://github.com/qdraw/tensorflow-face-object-detector-tutorial/blob/master/005__train.sh
