### ISSUE TITLE
Convert to tflite

### ISSUE THREAD

**Issue by jyotirmayghosh** [qdraw/tensorflow-face-object-detector-tutorial#4]
Hey, 
I was trying to convert the graphdef .pb to .tflite.
But to achieve that, i need the input_tensor and the output_tensor.

Can you help me with that?

**Comment by qdraw** [comment]
Hee I'm sorry but I don't know, did you already find it?

**Comment by jyotirmayghosh** [comment]
Yes I solved this issue.

Thank you

**Comment by qdraw** [comment]
@jyotirmayghosh could you please write down how you did it?
