### ISSUE TITLE
why only 9263?

### ISSUE THREAD

**Issue by gpqls** [qdraw/tensorflow-face-object-detector-tutorial#6]
Do you know why only a portion of the train image is converted to xml when there are approximately 12000 images? I need as many datasets as I can. I want to change all the images to xml.

**Comment by qdraw** [comment]
@gpqls This is why: https://developers.google.com/machine-learning/crash-course/training-and-test-sets/splitting-data

**Comment by qdraw** [comment]
@gpqls does this answer your question?

**Comment by gpqls** [comment]
No, I would like to know why only 7,000 of the approximately 12000 pieces of data in the train set will be converted.
Even for the val data, only a part is converted to xml.

**Comment by qdraw** [comment]
Then I would probably have a bug in the implementation
